version: '3.9'

services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
