version: '3.9'

services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - mynetwork

volumes:
  node_modules:

networks:
  mynetwork:
