# fly.toml app configuration file generated for warlock-backend on 2023-04-30T02:19:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "warlock-backend"
primary_region = "ord"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
